name: cat_trivia
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.2
  retrofit: ^4.0.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  json_annotation: ^4.8.0
  http: ^0.13.5
  dio: ^5.1.1
  equatable: ^2.0.5
  intl: ^0.18.0
  get_it: ^7.2.0
  shimmer: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  json_serializable: ^6.6.1
  retrofit_generator: ^6.0.0+1
  hive_generator: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  assets:
    - assets/images/placeholder.jpg

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

